name: Example Artifact Usage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make a file
        run: echo "Hello from Job 1!" > greeting.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: greeting-file
          path: greeting.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: greeting-file

      - name: List files
        run: ls -al

      - name: Read file
        run: cat greeting.txt
