name: First GitHub pipeline

on: 
  workflow_dispatch:
  
jobs:
  my-first-job:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Fetches your repository code

      - name: Print a message
        run: echo "Hello, GitHub Actions!"  # Prints a message
