name: First GitHub pipeline

on:
  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello, GitHub Actions!"
