name: Second GitHub Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Start job1
        run: echo "Job 1 - Step 1: Starting Job 1"

      - name: Step 2 - Print current directory
        run: pwd

      - name: Step 3 - List files
        run: ls -la

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Start job2
        run: echo "Job 2 - Step 1: Starting Job 2"

      - name: Step 2 - Print current date
        run: date

      - name: Step 3 - Print environment variables
        run: printenv
