name: Second GitHub Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 Checkout code
        uses: actions/checkout@v4

      - name: step2 Print a message from job1
        run: echo "This is job1 - Step 2"

      - name: step3 List files in repo
        run: ls -l

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message from job2
        run: echo "This is job2 - Hello from parallel job"

      - name: Show current date and time
        run: date
